FROM nodejs
ARG UID=1000
ARG GID=1000
ARG USER=app
ARG VERSION=latest
ENV UID=$UID
ENV GID=$GID
ENV USER=$USER
ENV VERSION=$VERSION

USER $USER
RUN cd /home/node && . ./nodeenv/bin/activate && npm config set prefix /home/node && npm install -g openclaw@$VERSION

#ENV PATH="/home/node/nodeenv/bin:$PATH"
ENTRYPOINT ["/home/node/nodeenv/bin/openclaw"]


